### ISSUE TITLE
Eine Art Tabelle mit auflistung alle Angestellten und Statistiken hinzufügen

### ISSUE THREAD

**Issue by BlackBadPinguin** [Dzefo/LiveOrganisation#1]

**Comment by Dzefo** [comment]
Aufgrund der Tatsache, dass es sich bei diesem Projekt um eine Eingabemaske und nicht um ein Dashboard handelt, muss ich diesen Vorschlag ablehnen. Sollte Interesse an einem Dashboard bestehen, bitte ich darum mich deswegen zu kontaktieren.
